import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./shared/navbar/Navbar";
import Footer from "./shared/footer/footer";
import Head from "next/head";
import Link from "next/link";
import Providers from "./_app";
import 'swiper/css';
import 'swiper/css/autoplay';
import 'swiper/css/mousewheel';
import 'swiper/css/navigation';
import "swiper/css/virtual";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <Head>
        <Link rel="preload" href="https://fonts.googleapis.com" as="font" />
        <Link
          rel="preload"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
          as="font"
        />
        <Link
          as="font"
          crossOrigin="anonymous"
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&family=Tajawal:wght@200;300;400;500;700;800;900&family=Zain:ital,wght@0,200;0,300;0,400;0,700;0,800;0,900;1,300;1,400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers> {/* Wrap children with Providers */}
          <Navbar />
          <div className="bg-[#FCFBFF]">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
